[project]
name = "turtles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typeguard>=4.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
